-- Location-integrity enforcement for stamp collection.
--
-- Policy:
--   1st mock-location session in 30 days: warning only
--   2nd: 15 minute collection cooldown
--   3rd: 1 hour collection cooldown
--   4th+: 24 hour collection cooldown
--
-- Repeated reports inside 60 seconds are treated as the same incident.
-- The cooldown is enforced in PostgreSQL so restarting the app or changing
-- the device clock cannot bypass it.

create table if not exists public.location_security_states (
  user_id uuid primary key references auth.users(id) on delete cascade,
  mock_violation_count integer not null default 0 check (mock_violation_count >= 0),
  last_mock_violation_at timestamptz,
  cooldown_started_at timestamptz,
  cooldown_until timestamptz,
  updated_at timestamptz not null default now()
);

alter table public.location_security_states enable row level security;
revoke all on table public.location_security_states from public, anon, authenticated;

create table if not exists public.location_security_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null,
  occurred_at timestamptz not null default now(),
  details jsonb not null default '{}'::jsonb
);

alter table public.location_security_events enable row level security;
revoke all on table public.location_security_events from public, anon, authenticated;

create index if not exists location_security_events_user_occurred_idx
  on public.location_security_events (user_id, occurred_at desc);

create or replace function public.report_location_integrity_violation(
  p_violation_type text
)
returns table (
  violation_count integer,
  cooldown_until timestamptz,
  cooldown_seconds integer
)
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_user_id uuid := auth.uid();
  v_now timestamptz := now();
  v_state public.location_security_states%rowtype;
  v_count integer;
  v_cooldown interval;
  v_until timestamptz;
begin
  if v_user_id is null then
    raise exception '認証が必要です.';
  end if;

  if p_violation_type <> 'mock_location' then
    raise exception '未対応の位置情報違反です.';
  end if;

  select *
    into v_state
  from public.location_security_states
  where user_id = v_user_id
  for update;

  if found
     and v_state.last_mock_violation_at is not null
     and v_now - v_state.last_mock_violation_at < interval '60 seconds' then
    return query
    select
      v_state.mock_violation_count,
      v_state.cooldown_until,
      greatest(
        0,
        ceil(extract(epoch from (v_state.cooldown_until - v_now)))::integer
      )
    where v_state.cooldown_until is not null
    union all
    select
      v_state.mock_violation_count,
      null::timestamptz,
      0
    where v_state.cooldown_until is null;
    return;
  end if;

  if not found
     or v_state.last_mock_violation_at is null
     or v_now - v_state.last_mock_violation_at >= interval '30 days' then
    v_count := 1;
  else
    v_count := v_state.mock_violation_count + 1;
  end if;

  v_cooldown := case
    when v_count <= 1 then interval '0 seconds'
    when v_count = 2 then interval '15 minutes'
    when v_count = 3 then interval '1 hour'
    else interval '24 hours'
  end;

  v_until := case
    when v_cooldown > interval '0 seconds' then v_now + v_cooldown
    else null
  end;

  insert into public.location_security_states (
    user_id,
    mock_violation_count,
    last_mock_violation_at,
    cooldown_started_at,
    cooldown_until,
    updated_at
  )
  values (
    v_user_id,
    v_count,
    v_now,
    case when v_until is null then null else v_now end,
    v_until,
    v_now
  )
  on conflict (user_id) do update
  set mock_violation_count = excluded.mock_violation_count,
      last_mock_violation_at = excluded.last_mock_violation_at,
      cooldown_started_at = excluded.cooldown_started_at,
      cooldown_until = excluded.cooldown_until,
      updated_at = excluded.updated_at;

  insert into public.location_security_events (
    user_id,
    event_type,
    occurred_at,
    details
  )
  values (
    v_user_id,
    p_violation_type,
    v_now,
    jsonb_build_object(
      'violation_count', v_count,
      'cooldown_seconds', extract(epoch from v_cooldown)::integer
    )
  );

  return query
  select
    v_count,
    v_until,
    extract(epoch from v_cooldown)::integer;
end;
$function$;

revoke execute on function public.report_location_integrity_violation(text)
from public, anon, authenticated;
grant execute on function public.report_location_integrity_violation(text)
to authenticated;

create or replace function public.get_my_location_security_state()
returns table (
  violation_count integer,
  cooldown_until timestamptz,
  cooldown_seconds integer
)
language sql
security definer
set search_path = ''
as $function$
  select
    s.mock_violation_count,
    s.cooldown_until,
    case
      when s.cooldown_until is null or s.cooldown_until <= now() then 0
      else ceil(extract(epoch from (s.cooldown_until - now())))::integer
    end
  from public.location_security_states s
  where s.user_id = auth.uid();
$function$;

revoke execute on function public.get_my_location_security_state()
from public, anon, authenticated;
grant execute on function public.get_my_location_security_state()
to authenticated;

create or replace function public.enforce_location_collection_cooldown()
returns trigger
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_state public.location_security_states%rowtype;
begin
  select *
    into v_state
  from public.location_security_states
  where user_id = new.user_id;

  if found
     and v_state.cooldown_until is not null
     and v_state.cooldown_until > now()
     and (
       v_state.cooldown_started_at is null
       or new.collected_at >= v_state.cooldown_started_at
     ) then
    raise exception '位置情報保護のためスタンプ獲得を一時停止しています.';
  end if;

  return new;
end;
$function$;

revoke execute on function public.enforce_location_collection_cooldown()
from public, anon, authenticated;

drop trigger if exists enforce_location_collection_cooldown
  on public.collection_history;

create trigger enforce_location_collection_cooldown
before insert on public.collection_history
for each row
execute function public.enforce_location_collection_cooldown();


-- Add server-backed impossible-movement incidents as a second location
-- integrity signal. Mock-location and movement incidents keep independent
-- counters, while sharing the same collection cooldown.
alter table public.location_security_states
  add column if not exists movement_violation_count integer not null default 0
    check (movement_violation_count >= 0),
  add column if not exists last_movement_violation_at timestamptz;

create or replace function public.report_location_integrity_violation(
  p_violation_type text
)
returns table (
  violation_count integer,
  cooldown_until timestamptz,
  cooldown_seconds integer
)
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_user_id uuid := auth.uid();
  v_now timestamptz := now();
  v_state public.location_security_states%rowtype;
  v_count integer;
  v_last_at timestamptz;
  v_cooldown interval;
  v_until timestamptz;
begin
  if v_user_id is null then
    raise exception '認証が必要です.';
  end if;

  if p_violation_type not in ('mock_location', 'implausible_movement') then
    raise exception '未対応の位置情報違反です.';
  end if;

  insert into public.location_security_states (user_id)
  values (v_user_id)
  on conflict (user_id) do nothing;

  select *
    into v_state
  from public.location_security_states
  where user_id = v_user_id
  for update;

  if p_violation_type = 'mock_location' then
    v_last_at := v_state.last_mock_violation_at;
    v_count := v_state.mock_violation_count;
  else
    v_last_at := v_state.last_movement_violation_at;
    v_count := v_state.movement_violation_count;
  end if;

  if v_last_at is not null
     and v_now - v_last_at < interval '60 seconds' then
    return query
    select
      v_count,
      v_state.cooldown_until,
      case
        when v_state.cooldown_until is null or v_state.cooldown_until <= v_now
          then 0
        else ceil(extract(epoch from (v_state.cooldown_until - v_now)))::integer
      end;
    return;
  end if;

  if v_last_at is null or v_now - v_last_at >= interval '30 days' then
    v_count := 1;
  else
    v_count := v_count + 1;
  end if;

  v_cooldown := case
    when v_count <= 1 then interval '0 seconds'
    when v_count = 2 then interval '15 minutes'
    when v_count = 3 then interval '1 hour'
    else interval '24 hours'
  end;

  v_until := case
    when v_cooldown > interval '0 seconds' then v_now + v_cooldown
    else null
  end;

  update public.location_security_states
  set mock_violation_count = case
        when p_violation_type = 'mock_location' then v_count
        else location_security_states.mock_violation_count
      end,
      last_mock_violation_at = case
        when p_violation_type = 'mock_location' then v_now
        else location_security_states.last_mock_violation_at
      end,
      movement_violation_count = case
        when p_violation_type = 'implausible_movement' then v_count
        else location_security_states.movement_violation_count
      end,
      last_movement_violation_at = case
        when p_violation_type = 'implausible_movement' then v_now
        else location_security_states.last_movement_violation_at
      end,
      cooldown_started_at = case
        when v_until is not null then v_now
        else location_security_states.cooldown_started_at
      end,
      cooldown_until = case
        when v_until is not null
          then greatest(coalesce(location_security_states.cooldown_until, v_until), v_until)
        when location_security_states.cooldown_until is not null and location_security_states.cooldown_until > v_now
          then location_security_states.cooldown_until
        else null
      end,
      updated_at = v_now
  where user_id = v_user_id
  returning location_security_states.cooldown_until into v_until;

  insert into public.location_security_events (
    user_id,
    event_type,
    occurred_at,
    details
  )
  values (
    v_user_id,
    p_violation_type,
    v_now,
    jsonb_build_object(
      'violation_count', v_count,
      'cooldown_seconds',
        case
          when v_until is null or v_until <= v_now then 0
          else ceil(extract(epoch from (v_until - v_now)))::integer
        end
    )
  );

  return query
  select
    v_count,
    v_until,
    case
      when v_until is null or v_until <= v_now then 0
      else ceil(extract(epoch from (v_until - v_now)))::integer
    end;
end;
$function$;

revoke execute on function public.report_location_integrity_violation(text)
from public, anon, authenticated;
grant execute on function public.report_location_integrity_violation(text)
to authenticated;
